name: "github auto-bot"
on:
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: "execution"
        run: echo "Salut je suis github auto-bot"

      - name: "Afficher mon nom"
        run: echo "Salut CyberTchak"

      - name: "Dire que tu fonctionne sur Ubuntu"
        run: echo "je fonctionne sur ubuntu"

