name: "github auto-bot"
on:
  push:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest

    steps: "salutation"
      - name: "execution"
        run: echo "Salut je suis github auto-bot"

